#!/bin/bash
# Regenerate THIRD-PARTY-NOTICES.md and App/Resources/acknowledgements.json
# from Package.resolved (plus scripts/model-acknowledgements.json for model
# weights). Maintainer tool: run after any dependency change, review the
# diff, commit the outputs. Requires network and an authenticated `gh`.
# Exits nonzero — and writes nothing — on copyleft or unresolvable licenses.
set -euo pipefail
cd "$(dirname "$0")/.."

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

python3 - > "$TMP/pins.tsv" <<'PY'
import json
for p in json.load(open("Package.resolved"))["pins"]:
    url = p["location"].removesuffix(".git")
    ver = p["state"].get("version") or p["state"].get("revision", "")[:12]
    print(f'{p["identity"]}\t{url}\t{ver}')
PY

unresolved=0
while IFS=$'\t' read -r identity url version; do
    path="${url#https://github.com/}"
    # /license reports the default branch, not the pinned ref; acceptable
    # for an audit doc — licenses effectively never change between pins.
    if ! gh api "repos/$path/license" > "$TMP/$identity.license.json" 2>/dev/null; then
        echo "UNRESOLVED: $identity ($url)" >&2
        unresolved=1
        continue
    fi
    for f in NOTICE NOTICE.txt; do
        if gh api "repos/$path/contents/$f" --jq .content 2>/dev/null \
             | base64 -d > "$TMP/$identity.notice" 2>/dev/null \
           && [ -s "$TMP/$identity.notice" ]; then
            break
        fi
        rm -f "$TMP/$identity.notice"
    done
done < "$TMP/pins.tsv"
if [ "$unresolved" -ne 0 ]; then
    echo "error: could not fetch licenses above — resolve by hand, then rerun." >&2
    exit 1
fi

python3 - "$TMP" <<'PY'
import base64, json, pathlib, sys

tmp = pathlib.Path(sys.argv[1])
pins = [l.split("\t") for l in (tmp / "pins.tsv").read_text().splitlines()]

COPYLEFT = ("GPL", "LGPL", "AGPL", "MPL", "EUPL", "CDDL")
# GitHub's license detector can't parse non-standard LICENSE files (e.g. a
# dual-license transition notice followed by two full license texts) and
# reports NOASSERTION/"Other" even when the license is unambiguously
# permissive. Verified by hand — see comment above each entry.
OVERRIDES = {
    # LICENSE file (github.com/modelcontextprotocol/swift-sdk, read via
    # `gh api repos/modelcontextprotocol/swift-sdk/license`) states the
    # project is transitioning from MIT to Apache-2.0: new code/spec
    # contributions are Apache-2.0; contributions from authors who haven't
    # granted relicensing consent remain MIT; docs (excluding specs) are
    # CC-BY-4.0. Every branch is permissive — no copyleft — so Apache-2.0
    # (the license for new contributions going forward) is used as the
    # summary SPDX id.
    "swift-sdk": "Apache-2.0",
}
entries = []
for identity, url, version in pins:
    info = json.loads((tmp / f"{identity}.license.json").read_text())
    spdx = (info.get("license") or {}).get("spdx_id") or "UNKNOWN"
    spdx = OVERRIDES.get(identity, spdx)
    text = base64.b64decode(info["content"]).decode("utf-8", "replace")
    cop = next((l.strip() for l in text.splitlines()
                if "copyright" in l.lower() and any(c.isdigit() for c in l)), None)
    notice_file = tmp / f"{identity}.notice"
    entries.append({
        "name": identity, "version": version, "license": spdx, "url": url,
        "copyright": cop,
        "notice": notice_file.read_text() if notice_file.exists() else None,
        "text": text,
    })

copyleft = [e["name"] for e in entries
            if any(e["license"].upper().startswith(c) for c in COPYLEFT)]
if copyleft:
    sys.exit(f"COPYLEFT FOUND — stop and report to the maintainer: {copyleft}")
unknown = [e["name"] for e in entries
           if e["license"] in ("UNKNOWN", "NOASSERTION", "OTHER")]
if unknown:
    sys.exit(f"Licenses needing hand review (not auto-classifiable): {unknown}")

entries.sort(key=lambda e: e["name"])
models = json.loads(pathlib.Path("scripts/model-acknowledgements.json").read_text())["models"]

out = [
    "# Third-party notices",
    "",
    "Luxicon is MIT-licensed (see LICENSE). It depends on the open-source",
    "packages and model weights below. This file is generated by",
    "`scripts/generate-notices.sh` — do not edit the package sections by",
    "hand; model credits live in `scripts/model-acknowledgements.json`.",
    "",
    "## Model weights",
    "",
    "Downloaded from Hugging Face on first use, run entirely on-device:",
    "",
]
for m in models:
    out.append(f"- **{m['name']}** — {m['license']} — {m['copyright']} — <{m['url']}>")
out += ["", "## Swift packages", ""]
for e in entries:
    out.append(f"### {e['name']} {e['version']}")
    out.append("")
    out.append(f"- License: {e['license']}")
    if e["copyright"]:
        out.append(f"- {e['copyright']}")
    out.append(f"- <{e['url']}>")
    out.append("")
    if e["notice"]:
        out += ["Upstream NOTICE file:", "", "```",
                e["notice"].rstrip(), "```", ""]
out += [
    "## License texts",
    "",
    "Full text of each license above, reproduced once per license type.",
    "The copyright lines in each package's section above apply to that",
    "package's copy.",
    "",
]
seen = {}
for e in entries:
    seen.setdefault(e["license"], e["text"])
for spdx in sorted(seen):
    out += [f"### {spdx}", "", "```", seen[spdx].rstrip(), "```", ""]

pathlib.Path("THIRD-PARTY-NOTICES.md").write_text("\n".join(out) + "\n")

pathlib.Path("App/Resources").mkdir(parents=True, exist_ok=True)
ack = {
    "packages": [{k: e[k] for k in ("name", "version", "license", "url", "copyright")}
                 for e in entries],
    "models": models,
}
pathlib.Path("App/Resources/acknowledgements.json").write_text(
    json.dumps(ack, indent=2, ensure_ascii=False) + "\n")

print(f"Wrote THIRD-PARTY-NOTICES.md ({len(entries)} packages, {len(models)} models)")
print("Wrote App/Resources/acknowledgements.json")
PY
